/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package listapv01questao01;

/**
 *
 * @author igor
 */
public class JanelaCliques extends javax.swing.JFrame {
int cliques = 0;
    /**
     * Creates new form JanelaCLiques
     */
    public JanelaCliques() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCliques = new javax.swing.JPanel();
        textoCliques = new javax.swing.JLabel();
        botaoCliques = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelCliques.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textoCliques.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        textoCliques.setText("Cliques: 0 ");

        botaoCliques.setBackground(new java.awt.Color(0, 204, 102));
        botaoCliques.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        botaoCliques.setText("Clique Aqui");
        botaoCliques.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        botaoCliques.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoCliques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCliquesActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("jButton1");

        javax.swing.GroupLayout painelCliquesLayout = new javax.swing.GroupLayout(painelCliques);
        painelCliques.setLayout(painelCliquesLayout);
        painelCliquesLayout.setHorizontalGroup(
            painelCliquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCliquesLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(painelCliquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCliquesLayout.createSequentialGroup()
                        .addComponent(botaoCliques, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCliquesLayout.createSequentialGroup()
                        .addGroup(painelCliquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(textoCliques))
                        .addGap(77, 77, 77))))
        );
        painelCliquesLayout.setVerticalGroup(
            painelCliquesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCliquesLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(textoCliques)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(botaoCliques, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCliques, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCliques, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCliquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCliquesActionPerformed
        cliques++;
        textoCliques.setText("Cliques: "+cliques);
    }//GEN-LAST:event_botaoCliquesActionPerformed

    /**
     * @param args the command line arguments
     */

      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCliques;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel painelCliques;
    private javax.swing.JLabel textoCliques;
    // End of variables declaration//GEN-END:variables
}
